// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzfwvM9Xvn9GXiBmGDQYpve7ehHnNo_Kk',
    appId: '1:335037135928:web:5cb2db5c1b461f34927acd',
    messagingSenderId: '335037135928',
    projectId: 'cityscene-dc3b3',
    authDomain: 'cityscene-dc3b3.firebaseapp.com',
    storageBucket: 'cityscene-dc3b3.appspot.com',
    measurementId: 'G-8XXZ2L4Q01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0CE6ujPWJP_zUBp6d_uZpygXw_tjJ1xU',
    appId: '1:335037135928:android:21fe83314ba5310e927acd',
    messagingSenderId: '335037135928',
    projectId: 'cityscene-dc3b3',
    storageBucket: 'cityscene-dc3b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAztNDFBFf7dfuRZhiL8Dobl591j7KiieQ',
    appId: '1:335037135928:ios:23eaadf8bc424cd1927acd',
    messagingSenderId: '335037135928',
    projectId: 'cityscene-dc3b3',
    storageBucket: 'cityscene-dc3b3.appspot.com',
    iosBundleId: 'com.flutterApplication23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAztNDFBFf7dfuRZhiL8Dobl591j7KiieQ',
    appId: '1:335037135928:ios:015e35ce01486472927acd',
    messagingSenderId: '335037135928',
    projectId: 'cityscene-dc3b3',
    storageBucket: 'cityscene-dc3b3.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
